name: ci
on:
  pull_request:
  push:
    branches:
    - master
jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [stable]
        include:
        - build: stable
          os: ubuntu-22.04
          rust: stable
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - run: cargo build --verbose
    - run: cargo doc --verbose
    - name: Run tests
      run: '(./start_cluster.sh &); sleep 20; env RUST_LOG=trace cargo test --verbose refresh -- --test-threads=1'
